config/routes.rb
Rails.application.routes.draw do
	namespace :api do
		resources :jobs
	end

  devise_for :users
  resources :jobs

  root 'pages#index'
  get 'pages/help'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
end

app/controllers/api/jobs_controller.rb
class Api::JobsController < ApplicationController
	skip_befoe_filter :verify_authenticity_token
	def index
		render json: Job.all
	end

	def show
		job = Job.find(params[:id])
		render json: list
	end

	# def create
	# 	job = Job.new(list_params)
	# 	if job.save
	# 		head 200
	# 	else
	# 		head 500
	# 	end
	# end

	private

	def list_params
		params.require("job").permit("title")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def after_sign_in_path_for(resources)
  	jobs_path
  end

  def after_sign_out_path_for(resources)
    jobs_path  	
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy ]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		if params[:category].blank?
			@jobs = Job.all.order("created_at DESC").paginate(page: params[:page], per_page: 7)
		else
			@category_id = Category.find_by(name: params[:category ]).id
			@jobs = Job.where(category_id: @category_id).order("created_at DESC").paginate(page: params[:page], per_page: 7)
		end
	end

	def show
	end

	def new
		@job = current_user.jobs.build
	end

	def create
		@job = current_user.jobs.build(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end 
	end

	def edit
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to root_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url, :category_id, :address)
	end

	def find_job
		@job = Job.find(params[:id])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def help
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		sanitize Kramdown::Document.new(text).to_html
	end
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
	def random_job_title
		titles = job_titles
		title = titles[rand(titles.length)]
	end

	private

	def job_titles
		titles = ["Stock Room Manager", "Web Developer", "Party Planner", "Wedding Singer", "Creative Director", "Musician", "Redback Remover", "Photographer", "Technical Advisor", "Personal Assistant", "Mechanic", "Game Tester", "Dental Associate", "Stock Broker", "Social Media Editor", "Customer Success", "Web Engineer", "Sales Consultant"]	
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: { class: 'form-horizontal' }) do |f|
	= f.collection_select :category_id, Category.all, :id, :name, input_html: { class: "dropdown-toggle" }
	= f.input :title, label: "Job Title", input_html: { class: "form-control" }, placeholder: random_job_title
	= f.input :description, label: "Job Description", input_html: { class: "form-control", placeholder: "We're looking for someone with the following skills..." }
	= f.input :company, label: "Your Company", input_html: {class: "form-control", placeholder: "Example Company" }
	= f.input :address, label: "Location", input_html: { class: "form-control", id: "address" }
	= f.input :url, label: "Link to Job", input_html: { class: "form-control" }, placeholder: "http://example.com/application"
	%br/
	= f.button :submit

app/views/jobs/edit.html.haml
.container
	%h1.text-primary Edit Job

	= render 'form'

	%hr

	%p The job description supports Kramdown. To learn how to make your description stand out, check out this <a target="_blank" href="http://kramdown.gettalong.org/quickref.html">Kramdown Quick Reference Guide</a>.

	= link_to "Back", job_path(params[:id]), class: "btn btn-small btn-default"

app/views/jobs/index.html.haml
.container
	- if @jobs.empty?
		%h1.text-center Sorry, there are no jobs to view.
	- else
		- @jobs.each do |job|
			%h2= link_to job.title, job, class: 'text-primary'
			%p.text-success= job.company
			%p.text-muted= "Created " + time_ago_in_words(job.created_at) + " ago"
			%hr

		= will_paginate @jobs, inner_window: 1, outer_window: 0

app/views/jobs/new.html.haml
.container
	%h1.text-primary New Job

	= render 'form'

	%hr

	%p The job description supports Kramdown. To learn how to make your description stand out, check out this <a target="_blank" href="http://kramdown.gettalong.org/quickref.html">Kramdown Quick Reference Guide</a>.

app/views/jobs/show.html.haml
.container
	%h1.text-primary= @job.title
	%p.text-success.job-description= markdown @job.description
	%p.text-success.lead= @job.company
	-if @job.address
		%p.text-success= "Located at: " + @job.address
	%p.text-muted= "Created " + time_ago_in_words(@job.created_at) + " ago"
	%button.btn.btn-default= link_to "Apply for Job!", @job.url, :target => "_blank"

	%hr

	#links
		= link_to "Back", :back, class: "btn btn-small btn-default"
		-if @job.user == current_user
			= link_to "Edit", edit_job_path(@job), class: "btn btn-small btn-default", data: {no_turbolink: true}
			= link_to "Delete", job_path(@job), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-small btn-default"

app/views/layouts/_footer.html.haml
%footer.footer.navbar.navbar-default
	.container-fluid
		.row
			%p.col-xs-11.col-sm-offset-1.col-sm-10.text-muted &copy;Alice Jobs 2015. All rights reserved. <a href="https://twitter.com/AliceJobsApp" target="_blank" class="icon"><span class="icon-twitter"></span></a>

			%p.col-xs-1.text-right= link_to "Help", pages_help_path

app/views/layouts/_header.html.haml
!!!
%html
	%head
		%title Alice Jobs
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
		= csrf_meta_tags
		<meta name=viewport content="width=device-width, initial-scale=1">
	%body
		%nav.navbar.navbar-default
			.container-fluid
				.navbar-brand
					= link_to "Alice Jobs", root_path

				%ul.nav.navbar-nav
					%li= link_to "All Jobs", jobs_path
				%ul.nav.navbar-nav.collapse.navbar-collapse
					- Category.all.each do |category|
						%li= link_to category.name, jobs_path(category: category.name)

				.collapse.navbar-collapse
					-if user_signed_in?
						= link_to "Log out", destroy_user_session_path, method: :delete, class: 'navbar-text navbar-right navbar-link'
						= link_to "New Job", new_job_path, class: 'navbar-text navbar-right navbar-link', data: {no_turbolink: true}
						= link_to "My Jobs", "", class: 'navbar-text navbar-right navbar-link', data: {no_turbolink: true}
					-else
						= link_to "Sign up", new_user_registration_path, class: 'navbar-text navbar-right navbar-link'
						= link_to "Log in", new_user_session_path, class: 'navbar-text navbar-right navbar-link'

app/views/layouts/application.html.haml
= render 'layouts/header'
				
.container
	-unless notice == nil
		%p.notice.text-success= notice
	-unless alert == nil
		%p.alert.text-danger= alert
= yield

= render 'layouts/footer'

app/views/pages/help.html.haml
.container
	%h1.text-center Welcome to the Alice Jobs support page.
	%p.lead.text-center.text-muted For all questions, please first refer to the FAQ, as we may already have an answer or we may currently be trying to address the issue. If you can't find your question, by all means contact us and we'll get back to you as soon as possible. To contact customer service, send an email to our <a href="mailto:alicejobsapp@gmail.com">Support Team</a>.

	%hr

.container
	.row
		.col-sm-5.col-sm-offset-1.col-xs-10
			%h3 FAQ
			.block
				%h4 How do I reset my password?
				%p.text-muted Currently, the ability to reset passwords has been disabled. This is due to the fact that we are currently working on an email issue and we can't send the email. So we decided to remove the link all together.

			.block
				%h4 Why doesn't my 'Apply for Job!' button work when it is clicked?
				%p.text-muted When creating a job, you need to enter a proper URL that leads to a place for a potential applicant to actually fill out an application or a place that they can get more information. If the URL is not filled in properly, the button won't work as intended.

			.block
				%h4 Is there a way for me to make my job posting stand out on the main jobs page?
				%p.text-muted At this time, no. We are currently still in a developmental stage and would prefer not to have that feature at this stage. In the future we will have either premium accounts or a way to pay for a specific post to stay at the top for a specific time. That feature will probably come in the future and there will be an update when it is released.

			.block
				%h4 Is there a limit on how many jobs I can post?
				%p.text-muted For now, the answer is no. In the future there will be a weekly or monthly limit to the amount of jobs you can post. This will be raised by purchasing a premium account. For now while we're in a developmental stage, feel free to post as much as you want. If this gets abused, we can easily impose a limit to each account.

			.block
				%h4 What is Kramdown and how do I use it?
				%p.text-muted Kramdown is a way to format text without using HTML. There are a lot of different formatting choices for you to use and it would be way too much to detail in this small FAQ. For more information, go to the <a href="http://kramdown.gettalong.org/quickref.html" target="_blank">Kramdown Quick Reference Guide</a>.

			.block
				%h4 Can I still create a job if not it's for a company?
				%p.text-muted Yes. If you're trying to hire someone for a personal job (mowing lawn, painting house, etc.), you can just use your own name in the Company Name section.

		.col-sm-5.col-xs-10
			%h3 Recent Updates
			.block
				%h4 May 16, 2015
				%ul.list-group
					%li.list-group-item.list-group-item-success Ability to add address
					%li.list-group-item.list-group-item-success Fixes issue with posts not showing when created before addresses were implemented
			.block
				%h4 May 10, 2015
				%ul.list-group
					%li.list-group-item.list-group-item-success Help/Support page created
					%li.list-group-item.list-group-item-success Fixed log in/out notices
					%li.list-group-item.list-group-item-success Now redirects to all jobs page after log in/out
					%li.list-group-item.list-group-item-success Footer added

app/views/pages/index.html.haml
.jumbotron
	.container
		%h1.text-center Alice Jobs!
		%h3.text-center.text-muted Connecting real people with real jobs.
		= link_to "Find Job Now!", jobs_path, class: "btn btn-lg btn-info col-xs-4 col-xs-offset-4"

.container
	%p.lead.text-center Why struggle trying to find great, well paying jobs when you can easily discover them all in one place? 
	%hr
	.container-fluid
		.row
			.col-sm-offset-1.col-sm-5.col-xs-10
				%h4 Why choose us?
				%p<
					Alice Jobs is a great place to find local jobs in Alice Springs, Australia. We've got something for you whether you're a local resident looking to work full-time for a premier company, or you're traveling through looking to find a place to make some cash for a few months before moving on. We've got everything here in one place. Our goal is to make the process of finding a job as easy and manageable as possible. 
					= link_to " Learn more now!", pages_help_path
					
			.col-sm-5.col-xs-10
				%h4 Traveling to Alice?
				%p<
					For people moving to Alice Springs or traveling for a short period, there are jobs to fit everyone's needs. One of the more difficult parts of going to a new place is finding open jobs. One of our main goals is to make that transition easier by providing a single, consolidated place to post and view available jobs. We provide the first and last stop in the hunt for a new job. 
					= link_to " Learn more now!", pages_help_path